version: '1.0'
steps:
  RunningDeployScript:
    title: Running Deploy Script
    type: deploy
    kind: kubernetes
    cluster: cluster-1@Emirates
    namespace: default
    when:
      branch:
        only:
          - master
    service: demochat
